namespace ERASManager.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FBHPDataHolderWFB_Updated : DbMigration
    {
        public override void Up()
        {
            AlterColumn("dbo.FBHPDataHolderWFBs", "F1", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F2", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F3", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F4", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F5", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F6", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F7", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F8", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F9", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F10", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F11", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F12", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F13", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F14", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F15", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F16", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F17", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F18", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F19", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F20", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F21", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F22", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F23", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F24", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F25", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F26", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F27", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F28", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F29", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F30", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F31", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F32", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F33", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F34", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F35", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F36", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F37", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F38", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F39", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F40", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F41", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F42", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F43", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F44", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F45", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F46", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F47", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F48", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F49", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F50", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F51", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F52", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F53", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F54", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F55", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F56", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F57", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F58", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F59", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F60", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F61", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F62", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F63", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F64", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F65", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F66", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F67", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F68", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F69", c => c.String());
            AlterColumn("dbo.FBHPDataHolderWFBs", "F70", c => c.String());
        }
        
        public override void Down()
        {
            AlterColumn("dbo.FBHPDataHolderWFBs", "F70", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F69", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F68", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F67", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F66", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F65", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F64", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F63", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F62", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F61", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F60", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F59", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F58", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F57", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F56", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F55", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F54", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F53", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F52", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F51", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F50", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F49", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F48", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F47", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F46", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F45", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F44", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F43", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F42", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F41", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F40", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F39", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F38", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F37", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F36", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F35", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F34", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F33", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F32", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F31", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F30", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F29", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F28", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F27", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F26", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F25", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F24", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F23", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F22", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F21", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F20", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F19", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F18", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F17", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F16", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F15", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F14", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F13", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F12", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F11", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F10", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F9", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F8", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F7", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F6", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F5", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F4", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F3", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F2", c => c.String(maxLength: 150));
            AlterColumn("dbo.FBHPDataHolderWFBs", "F1", c => c.String(maxLength: 150));
        }
    }
}
